<html>
<head>
<title>Sistema de stock San Mateo</title>
<body bgcolor="#000065">
  <table border=0 width="100%" height="100%">
	<TR>
	  <td></td>
	  <TD align="center" valign="middle">
	    <form action="syslogin.php">
	     <table border=0 width="300" height="100" bgcolor="#fffed2" cellspacing="1" cellpadding="5">
	         <TR bgcolor="#000065">
		     <TD bgcolor="#709BC9" colspan="2" align="center">
		        <font color="#FFFED2"><b>Ingreso al sistema</b></font>
		     </TD>
		 </TR>
	         <TR bgcolor="#000065">
		     <TD align="right">
		        <font color="#FFFED2"><b>Usuario</b></font>
		     </TD>
		     <TD align="center">
		        <input type="text" lenght=15 name="usuario">
		     </TD>
		 </TR>
	         <TR bgcolor="#000065">
		     <TD align="right">
		        <font color="#FFFED2"><b>Clave</b></font>
		     </TD>
		     <TD align="center">
		        <input type="password" lenght=15 name="clave">
		     </TD>
		 </TR>	     
	         <TR bgcolor="#000065">
		     <TD bgcolor="#709BC9" colspan="2" align="center">
		        <input type="submit" value="Entrar">
		     </TD>
		 </TR>
	     </table>
	    </form>
	  </TD>
	  <td></td>
	 </TR>
  </table>
</body>
</head>
</html>

