#!/bin/sh
##############################################################
# LICENSE
# =======
# Copyright (C) 2005 Martijn Loots, Cosix Automatisering, NL
#
# PhpCodeBuster is a PHP code obfuscator, written in PHP.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
# A copy of the GNU General Public License is available at
# http://www.gnu.org/copyleft/gpl.html
##############################################################
if [ ! -d $HOME/bustdir ]; then
  if ! mkdir $HOME/bustdir; then
    echo "$0: error: cannot create $HOME/bustdir"
    exit 1
  fi
fi

/usr/bin/php -f $HOME/bin/bust.php $1 > $HOME/bustdir/$1
